#!/usr/bin/env python3
"""Regenerate public/assets/css/fonts.css and the woff2 files beside it.

The site self-hosts its webfonts rather than linking Google Fonts, so that the faces
arrive before first paint and nothing re-lays-out mid-session. Run this only when the
families or weights in the design change; the output is committed.

    python scripts/fetch-fonts.py

Subsets are limited to what the content uses: latin, latin-ext (Diǎn Cuì) and greek
(lambda-PR, mu_max, theta in the protocols). CJK is in neither family and falls back to a
system face. unicode-range is preserved, so a visitor only downloads a subset if the page
contains a character from it.
"""
import re, os, urllib.request, io

UA = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}
URL = ("https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500;600;700"
       "&family=Inter:wght@400;500;600;700&display=swap")
KEEP = {"latin", "latin-ext", "greek", "greek-ext"}
ROOT = os.path.join(os.path.dirname(__file__), "..")
FONTS = os.path.join(ROOT, "public/assets/fonts")
OUT = os.path.join(ROOT, "public/assets/css/fonts.css")

HEADER = """/* Self-hosted webfonts. Regenerated by scripts/fetch-fonts.py — do not hand-edit.
 * See the header comment in that script for why these are not loaded from Google.
 */
"""

def main():
    css = urllib.request.urlopen(urllib.request.Request(URL, headers=UA), timeout=30).read().decode()
    os.makedirs(FONTS, exist_ok=True)
    out = []
    for subset, block in re.findall(r"/\*\s*([a-z\-]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S):
        if subset not in KEEP:
            continue
        fam = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        wt = re.search(r"font-weight:\s*(\d+)", block).group(1)
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
        name = "%s-%s-%s.woff2" % (fam.lower().replace(" ", "-"), wt, subset)
        path = os.path.join(FONTS, name)
        if not os.path.exists(path):
            open(path, "wb").write(
                urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=30).read())
        ur = re.search(r"unicode-range:\s*([^;]+);", block)
        out.append("@font-face{\n  font-family:'%s';\n  font-style:normal;\n  font-weight:%s;\n"
                   "  font-display:swap;\n  src:url('../fonts/%s') format('woff2');\n%s}\n"
                   % (fam, wt, name, ("  unicode-range:%s;\n" % ur.group(1)) if ur else ""))
    io.open(OUT, "w", encoding="utf-8", newline="\n").write(HEADER + "".join(out))
    print("wrote %s (%d faces)" % (OUT, len(out)))

if __name__ == "__main__":
    main()
